### ISSUE TITLE
MFM not works with MythicMobs

### ISSUE THREAD

**Issue by Poweringg** [chocolf/MoneyFromMobs#11]
when i add MythicMobs plugin, then MFM stopped working, and when i kill something i got this error:

```
[14:31:46 ERROR]: Could not pass event EntityDeathEvent to MoneyFromMobs v4.41
java.lang.NoClassDefFoundError: io/lumine/xikage/mythicmobs/MythicMobs
        at me.chocolf.moneyfrommobs.manager.DropsManager.getEntityName(DropsManager.java:195) ~[MoneyFromMobs.jar:?]
        at me.chocolf.moneyfrommobs.listener.DeathListeners.onEntityDeath(DeathListeners.java:44) ~[MoneyFromMobs.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor334.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-247]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:878) ~[paper-1.18.2.jar:git-Paper-247]
        at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1726) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1624) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1452) ~[?:?]
        at net.minecraft.world.entity.player.Player.attack(Player.java:1278) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2033) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$5.a(ServerGamePacketListenerImpl.java:2531) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2458) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-247]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1399) ~[paper-1.18.2.jar:git-Paper-247]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-247]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1376) ~[paper-1.18.2.jar:git-Paper-247]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1369) ~[paper-1.18.2.jar:git-Paper-247]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1347) ~[paper-1.18.2.jar:git-Paper-247]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1229) ~[paper-1.18.2.jar:git-Paper-247]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-247]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: io.lumine.xikage.mythicmobs.MythicMobs
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 33 more
```

Server Version: org.bukkit.craftbukkit.v1_18_R2 (Paper) MC 1.18.2
Mythicmobs Plugin Version: 5.0.1
mythicmobs Plugin Build: e876be12
moneyFromMobs version: 4.41
i have vault, essentialsX, luckPerms installed.

**Comment by chocolf** [comment]
Fixed in the latest update!

**Comment by Poweringg** [comment]
Works perfectly. Thank you, keep up your work!
