### ISSUE TITLE
Mobs killed by offline player projectiles error

### ISSUE THREAD

**Issue by h266579110** [chocolf/MoneyFromMobs#13]
PaperMC 1.18.2-267, MFM 4.42

```
[13:09:24 ERROR]: Could not pass event EntityDeathEvent to MoneyFromMobs v4.42
me.lucko.luckperms.bukkit.vault.ServerThreadLookupException: A Vault API request has been made on the main server thread that LuckPerms cannot safely respond to.
This is NOT a bug - please do not report it to LuckPerms.
Instead, please carefully read the information given below.

LuckPerms cannot respond to the request because to do so:
- it needs to lookup user data for 'dd778778-86ef-4207-809c-794c79850f1e' (an offline player) from the database

Performing this lookup on the main server thread would cause your server to lag.
There are two solutions to this problem:
  a) Ask the author of the plugin making the request to perform Vault calls for
     offline players "asynchronously" (using the scheduler). Additionally, prefer
     using the methods that accept 'Player' or 'OfflinePlayer' instead of usernames.
     You should be able to identify the plugin making the request in the trace below.
  b) As a server admin, you can disable this exception by setting 'vault-unsafe-lookups'
     to true in the LuckPerms configuration file. However, please use this only as
     a last resort.
        at me.lucko.luckperms.bukkit.vault.LuckPermsVaultPermission.lookupUser(LuckPermsVaultPermission.java:155) ~[?:?]
        at me.lucko.luckperms.bukkit.vault.LuckPermsVaultPermission.userGetGroups(LuckPermsVaultPermission.java:259) ~[?:?]
        at me.lucko.luckperms.bukkit.vault.AbstractVaultPermission.getPlayerGroups(AbstractVaultPermission.java:419) ~[?:?]
        at me.chocolf.moneyfrommobs.manager.MultipliersManager.applyPermissionGroupMultiplier(MultipliersManager.java:115) ~[MoneyFromMobs.jar:?]
        at me.chocolf.moneyfrommobs.manager.MultipliersManager.applyMultipliers(MultipliersManager.java:60) ~[MoneyFromMobs.jar:?]
        at me.chocolf.moneyfrommobs.listener.DeathListeners.onEntityDeath(DeathListeners.java:58) ~[MoneyFromMobs.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1095.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-267]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:878) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1726) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1624) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1452) ~[?:?]
        at net.minecraft.world.entity.monster.Zombie.hurt(Zombie.java:317) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R2.entity.CraftLivingEntity.damage(CraftLivingEntity.java:363) ~[paper-1.18.2.jar:git-Paper-267]
        at xyz.xenondevs.nova.tileentity.impl.mob.MobKiller.handleTick(MobKiller.kt:112) ~[Nova-0.8.9.jar:?]
        at xyz.xenondevs.nova.tileentity.TileEntityManager$init$4.invoke(TileEntityManager.kt:95) ~[Nova-0.8.9.jar:?]
        at xyz.xenondevs.nova.tileentity.TileEntityManager$init$4.invoke(TileEntityManager.kt:95) ~[Nova-0.8.9.jar:?]
        at xyz.xenondevs.nova.util.SchedulerUtilsKt$runTaskTimerSynchronized$1.run(SchedulerUtils.kt:29) ~[Nova-0.8.9.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-267]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1531) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-267]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by chocolf** [comment]
Fixed in version 4.6 of MFM thanks for reporting the bug!
