### ISSUE TITLE
Chat spam error

### ISSUE THREAD

**Issue by Ferrarex** [chocolf/MoneyFromMobs#14]
every time a mob dies this happen:
ERROR:] Could not pass event EntityDeathEvent to MoneyFromMobs v4.42
java.lang.NoClassDefFoundError: io/lumine/mythic/bukkit/MythicBukkit
        at me.chocolf.moneyfrommobs.manager.DropsManager.getEntityName(DropsManager.java:195) ~[MoneyFromMobs.jar:?]
        at me.chocolf.moneyfrommobs.listener.DeathListeners.onEntityDeath(DeathListeners.java:44) ~[MoneyFromMobs.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1222.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-82]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:868) ~[paper-1.18.1.jar:git-Paper-82]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:860) ~[paper-1.18.1.jar:git-Paper-82]
        at net.minecraft.world.entity.decoration.ArmorStand.kill(ArmorStand.java:757) ~[?:?]
        at net.minecraft.server.commands.KillCommand.kill(KillCommand.java:32) ~[?:?]
        at net.minecraft.server.commands.KillCommand.register(KillCommand.java:25) ~[?:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[paper-1.18.1.jar:?]
        at net.minecraft.commands.CommandFunction$CommandEntry.execute(CommandFunction.java:134) ~[?:?]
        at net.minecraft.commands.CommandFunction$CommandEntry.execute(CommandFunction.java:128) ~[?:?]
        at net.minecraft.server.ServerFunctionManager$QueuedCommand.execute(ServerFunctionManager.java:228) ~[?:?]
        at net.minecraft.server.ServerFunctionManager$ExecutionContext.runTopCommand(ServerFunctionManager.java:187) ~[?:?]
        at net.minecraft.server.ServerFunctionManager.execute(ServerFunctionManager.java:95) ~[?:?]
        at net.minecraft.server.ServerFunctionManager.execute(ServerFunctionManager.java:78) ~[?:?]
        at net.minecraft.server.ServerFunctionManager.executeTagFunctions(ServerFunctionManager.java:71) ~[?:?]
        at net.minecraft.server.ServerFunctionManager.tick(ServerFunctionManager.java:51) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1551) ~[paper-1.18.1.jar:git-Paper-82]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-82]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-82]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-82]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-82]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: io.lumine.mythic.bukkit.MythicBukkit
        ... 27 more
        
        
i am using the last ver of the plugin (4.42), and my server is paper 1.18.1 (newest build)

**Comment by chocolf** [comment]
You need to use the latest version of MythicMobs
