### ISSUE TITLE
Could not pass event PlayerAttemptPickupItemEvent to MoneyFromMobs v4.01

### ISSUE THREAD

**Issue by BenjaminHoegh** [chocolf/MoneyFromMobs#4]
Paper version git-Paper-"a7cddc4" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
MoneyFromMobs v4.01

```
[09:37:43 ERROR]: Could not pass event PlayerAttemptPickupItemEvent to MoneyFromMobs v4.01
java.lang.NullPointerException: Cannot invoke "net.milkbowl.vault.economy.Economy.depositPlayer(org.bukkit.OfflinePlayer, double)" because the return value of "me.chocolf.moneyfrommobs.MoneyFromMobs.getEcon()" is null
        at me.chocolf.moneyfrommobs.manager.PickUpManager.giveMoney(PickUpManager.java:180) ~[?:?]
        at me.chocolf.moneyfrommobs.listener.PaperListeners.onAttemptToPickUp(PaperListeners.java:46) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor146.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.jar:git-Paper-"a7cddc4"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.jar:git-Paper-"a7cddc4"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.jar:git-Paper-"a7cddc4"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.jar:git-Paper-"a7cddc4"]
        at net.minecraft.world.entity.item.ItemEntity.playerTouch(ItemEntity.java:402) ~[?:?]
        at net.minecraft.world.entity.player.Player.touch(Player.java:617) ~[?:?]
        at net.minecraft.world.entity.player.Player.aiStep(Player.java:583) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2874) ~[?:?]
        at net.minecraft.world.entity.player.Player.tick(Player.java:270) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:671) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:317) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:399) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:196) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1576) ~[patched_1.17.jar:git-Paper-"a7cddc4"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:477) ~[patched_1.17.jar:git-Paper-"a7cddc4"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1404) ~[patched_1.17.jar:git-Paper-"a7cddc4"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[patched_1.17.jar:git-Paper-"a7cddc4"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-"a7cddc4"]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by lokka30** [comment]
Do you have Vault installed?

You also need an Economy plugin that uses Vault - Essentials has this for example

**Comment by ErythroCraft** [comment]
@chocolf please close this.

It is version Paper mc 1.17 and fixed in later versions.
