### ISSUE TITLE
Could not pass event EntityDeathEvent with EventException Null

### ISSUE THREAD

**Issue by marcjoancr** [chocolf/MoneyFromMobs#7]
```
[ERROR] Could not pass event EntityDeathEvent to MoneyFromMobs v4.3
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:789) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
at net.minecraft.world.entity.EntityLiving.f(EntityLiving.java:1664) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
at net.minecraft.world.entity.EntityLiving.die(EntityLiving.java:1605) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
at net.minecraft.world.entity.EntityLiving.damageEntity(EntityLiving.java:1436) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
at net.minecraft.world.entity.EntityInsentient.attackEntity(EntityInsentient.java:1517) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
at net.minecraft.world.entity.animal.EntityFox$l.a(EntityFox.java:1100) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
at net.minecraft.world.entity.ai.goal.PathfinderGoalMeleeAttack.e(SourceFile:134) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
at net.minecraft.world.entity.ai.goal.PathfinderGoalWrapped.e(SourceFile:55) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?]
at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:?]
at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[?:?]
at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
at net.minecraft.world.entity.ai.goal.PathfinderGoalSelector.doTick(SourceFile:88) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
at net.minecraft.world.entity.EntityInsentient.doTick(EntityInsentient.java:807) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
at net.minecraft.world.entity.EntityLiving.movementTick(EntityLiving.java:3079) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
at net.minecraft.world.entity.EntityInsentient.movementTick(EntityInsentient.java:608) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
at net.minecraft.world.entity.EntityAgeable.movementTick(EntityAgeable.java:153) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
at net.minecraft.world.entity.animal.EntityAnimal.movementTick(EntityAnimal.java:61) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
at net.minecraft.world.entity.animal.EntityFox.movementTick(EntityFox.java:230) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
at net.minecraft.world.entity.EntityLiving.tick(EntityLiving.java:2808) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
at net.minecraft.world.entity.EntityInsentient.tick(EntityInsentient.java:376) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
at net.minecraft.world.entity.animal.EntityFox.tick(EntityFox.java:526) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
at net.minecraft.server.level.WorldServer.entityJoinedWorld(WorldServer.java:815) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
at net.minecraft.world.level.World.a(World.java:697) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
at net.minecraft.server.level.WorldServer.lambda$11(WorldServer.java:527) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
at net.minecraft.world.level.entity.EntityTickList.a(SourceFile:54) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
at net.minecraft.server.level.WorldServer.doTick(WorldServer.java:508) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1299) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1202) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1035) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "io.lumine.xikage.mythicmobs.api.bukkit.BukkitAPIHelper.isMythicMob(org.bukkit.entity.Entity)" because the return value of "io.lumine.xikage.mythicmobs.MythicMobs.getAPIHelper()" is null
at me.chocolf.moneyfrommobs.manager.DropsManager.getEntityName(DropsManager.java:227) ~[?:?]
at me.chocolf.moneyfrommobs.listener.DeathListeners.onEntityDeath(DeathListeners.java:47) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
... 42 more
```

**Comment by chocolf** [comment]
Hey, I know I already helped you in Spigot DMs, but just in case anyone else is having this problem, The latest version of MythicMobs does not seem to work without using PaperMC. In order to fix this, you need to switch from Spigot to Paper https://papermc.io/downloads
